# Generated by Django 4.1.5 on 2023-01-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_remove_category_parent_remove_product_ctg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkan',
            name='tkan_img',
        ),
        migrations.AddField(
            model_name='product',
            name='ctg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sayt.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductTkanImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Tkan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.product')),
                ('tkan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.tkan')),
            ],
        ),
    ]
