# Generated by Django 4.1.5 on 2023-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0004_remove_tkan_tkan_img_product_ctg_producttkanimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkan',
            name='pro',
        ),
    ]
