# Generated by Django 4.1.5 on 2023-01-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_remove_tkan_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTkanAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.producttkanimg')),
            ],
        ),
    ]
